id: multilingual_research_i18n
learningObjectives: 
- Analyzing the best i18n library
hints:
- Research and come up with the most popular(or like top 3) library to implement internationalization 
- Try a library that fits with redux and also supports i18n
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: 'We are in a nightmare! Our website is failing to support French and its left a million of our French users stranded and frustrated. Did somebody start selling some rare golden croissant ?? I have no clue where we got such a huge spike of french users from but this is a serious issue to the reputation and respect of our marketplace.'
        delay: 2000 
      - text: 'Also When I am extremely scared I try to write stories and speak in a royal tone. So hold tight to your keyboard and here it goes....'
        delay: 4000 
      - text: "The senior developer(Me), a regal figure in the realm of code, summoned the junior developer(You) to his chambers. The junior developer, a mere squire in the realm of code, approached with fear."
      - text: 'The senior developer spoke in a booming voice, "Squire, I have a task of great importance for you. The marketplace of Anythink has seen a heavy influx of French subjects, and they are unable to navigate our lands due to the lack of French language support."'
      - text: "You, my squire, don't be scared. I know you are young in this realm but I have faith in you. So go right now to the jungle of libraries and figure out the best internationalization(i18n) library for our setup."
      - text: "My good developer, don't be hasty and be sure that you to read the documentation while you are hunting and only after your mind have conquered its knowledge, return to me with its name so that I may use my insights to guide you further."
    
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: redux-i18n|i18next|react-redux-i18n|react-i18next|react-intl-universal|i18n-react
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Well done, young developer. You have made a wise choice."
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Try again! my squire and dont lose hope. I'm sure you'll figure this out."
              delay: 2500
