id: multilingual_implement_i18n
learningObjectives: 
- Learning to implement i18n
hints:
- Are you sure all the text of the navbar is translated even the selector values ?  
- Make sure to add the library in your package.json
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Magnificent my squire!  But the journey has just begun. It is now time that you conquer the most important task in this adventurous quest. So go forth and delve deep into the documentation of the library and master its intricacies."
        delay: 7000
      - text: "After your mind has won over the war of understanding the implementation, setup i18n with care in our subtle and vast codebase and translate **all the text in the header**.  So when the language on the button of selection changes all the text of the header should also follow heed and change."
      - text: "Then open a PR, my loyal squire, and let me know so that I may review thy code and ensure its righteousness"
        delay: 2000
githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    - puppeteer@18.1.0
    - languagedetect
    testFile: "navbar-language.test.js"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "On it, my squire. I shall review the changes with utmost urgency and provide my royal feedback."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: keen
              message: "On it, my squire. I shall review the changes with utmost urgency and provide my royal feedback."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Excellent work @${user.githubuser}, my faithful squire. Thou may now merge the pull request."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: keen
              message: "Excellent work @${user.githubuser}, my faithful squire. Thou may now merge the pull request."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Ensure that thy fix pass all the checks and tests, then try again, good developer. Do not disappoint me."
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Verily, it seems that this alteration in code doth not fix the problem at hand. I beseech thee, my trusty developer, to take another look and see if perchance there is another solution to be found."
        github_pr_merged:
          do:
          - actionId: finish_step
