id: multilingual_translate_authpage
learningObjectives: 
- Handling translations across various components 
hints:
- Make sure you have added the required id and values specified and the value also changes 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Now just translate the login and register page so that users can easily register and start shopping"
        delay: 1500
      - text: "Can you please transalte and **open a PR**, so we can release a new version to production?"
        delay: 1500
githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    - puppeteer@18.1.0
    - languagedetect
    testFile: "auth-page-language.test.js"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "On it, I'll review the changes right away."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: keen
              message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: keen
              message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Make sure your fix passes all the checks, then try again please."
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Looks like this code change didn’t fix the problem. Can you take a second look?"
        github_pr_merged:
          do:
          - actionId: finish_step
